import sys
from extracthendrix.config.variables.utils import NativeVariable

"""
In this file you will find native variables names in PEAROME. 
If you need to implement a new variable, please give the native variable here.

See Documentation in arome.py for more details.
"""

model = "PEAROME"

vars = {'zs': dict(name='Geometrical height', shortName='h', parameterCategory=3, parameterNumber=6,
                   typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        't2m': dict(name='2 metre temperature', shortName='2t', parameterCategory=0, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=2, productDefinitionTemplateNumber=1),
        't0m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                    typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        't10m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                     typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        't20m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                     typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        't35m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                     typeOfFirstFixedSurface=103, level=35, productDefinitionTemplateNumber=1),
        't50m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                     typeOfFirstFixedSurface=103, level=50, productDefinitionTemplateNumber=1),
        't75m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                     typeOfFirstFixedSurface=103, level=75, productDefinitionTemplateNumber=1),
        't100m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=100, productDefinitionTemplateNumber=1),
        't150m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=150, productDefinitionTemplateNumber=1),
        't200m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=200, productDefinitionTemplateNumber=1),
        't250m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=250, productDefinitionTemplateNumber=1),
        't375m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=375, productDefinitionTemplateNumber=1),
        't500m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=500, productDefinitionTemplateNumber=1),
        't625m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=625, productDefinitionTemplateNumber=1),
        't750m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=750, productDefinitionTemplateNumber=1),
        't875m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                      typeOfFirstFixedSurface=103, level=875, productDefinitionTemplateNumber=1),
        't1000m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=1000, productDefinitionTemplateNumber=1),
        't1125m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=1125, productDefinitionTemplateNumber=1),
        't1250m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=1250, productDefinitionTemplateNumber=1),
        't1375m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=1375, productDefinitionTemplateNumber=1),
        't1500m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=1500, productDefinitionTemplateNumber=1),
        't1750m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=1750, productDefinitionTemplateNumber=1),
        't2000m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=2000, productDefinitionTemplateNumber=1),
        't2250m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=2250, productDefinitionTemplateNumber=1),
        't2500m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=2500, productDefinitionTemplateNumber=1),
        't2750m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=2750, productDefinitionTemplateNumber=1),
        't3000m': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=3000, productDefinitionTemplateNumber=1),
        't100hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=100, productDefinitionTemplateNumber=1),
        't125hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=125, productDefinitionTemplateNumber=1),
        't150hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=150, productDefinitionTemplateNumber=1),
        't175hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=175, productDefinitionTemplateNumber=1),
        't200hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        't225hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=225, productDefinitionTemplateNumber=1),
        't250hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        't275hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=275, productDefinitionTemplateNumber=1),
        't300hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        't350hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        't400hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        't450hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=450, productDefinitionTemplateNumber=1),
        't500hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        't550hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        't600hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        't650hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=650, productDefinitionTemplateNumber=1),
        't700hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        't750hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        't800hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        't850hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        't900hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        't925hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        't950hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                        typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        't1000hpa': dict(name='Temperature', shortName='t', parameterCategory=0, parameterNumber=0,
                         typeOfFirstFixedSurface=100, level=1000, productDefinitionTemplateNumber=1),
        'maxt2m': dict(name='2 metre temperature', shortName='2t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=2, productDefinitionTemplateNumber=11,
                       typeOfStatisticalProcessing=2),
        'mint2m': dict(name='2 metre temperature', shortName='2t', parameterCategory=0, parameterNumber=0,
                       typeOfFirstFixedSurface=103, level=2, productDefinitionTemplateNumber=11,
                       typeOfStatisticalProcessing=3),
        'isoT27315cK': dict(name='Geometrical height', shortName='h', parameterCategory=3, parameterNumber=6,
                         typeOfFirstFixedSurface=197, productDefinitionTemplateNumber=1,
                         scaleFactorOfFirstFixedSurface=2, scaledValueOfFirstFixedSurface=27315),
        'isoT26315cK': dict(name='Geometrical height', shortName='h', parameterCategory=3, parameterNumber=6,
                            typeOfFirstFixedSurface=197, productDefinitionTemplateNumber=1,
                            scaleFactorOfFirstFixedSurface=2, scaledValueOfFirstFixedSurface=26315),
        'isoT26115cK': dict(name='Geometrical height', shortName='h', parameterCategory=3, parameterNumber=6,
                            typeOfFirstFixedSurface=197, productDefinitionTemplateNumber=1,
                            scaleFactorOfFirstFixedSurface=2, scaledValueOfFirstFixedSurface=26115),
        'isoT25315cK': dict(name='Geometrical height', shortName='h', parameterCategory=3, parameterNumber=6,
                            typeOfFirstFixedSurface=197, productDefinitionTemplateNumber=1,
                            scaleFactorOfFirstFixedSurface=2, scaledValueOfFirstFixedSurface=25315),
        'isowetbt27315cK': dict(name='Geometrical height', shortName='h', parameterCategory=3,
                                parameterNumber=6, typeOfFirstFixedSurface=198,
                                productDefinitionTemplateNumber=1, scaleFactorOfFirstFixedSurface=2,
                                scaledValueOfFirstFixedSurface=27315),
        'isowetbt27415cK': dict(name='Geometrical height', shortName='h', parameterCategory=3,
                                parameterNumber=6,
                                typeOfFirstFixedSurface=198, productDefinitionTemplateNumber=1,
                                scaleFactorOfFirstFixedSurface=2, scaledValueOfFirstFixedSurface=27415),
        'isowetbt27465cK': dict(name='Geometrical height', shortName='h', parameterCategory=3,
                                parameterNumber=6,
                                typeOfFirstFixedSurface=198, productDefinitionTemplateNumber=1,
                                scaleFactorOfFirstFixedSurface=2, scaledValueOfFirstFixedSurface=27465),
        'rprate': dict(name='Rain precipitation rate', shortName='rprate', parameterCategory=1,
                       parameterNumber=65, typeOfFirstFixedSurface=1, level=0,
                       productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'sprate': dict(name='Snow precipitation rate', shortName='sprate', parameterCategory=1,
                       parameterNumber=66, typeOfFirstFixedSurface=1, level=0,
                       productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'gprate': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=75,
                       typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                       typeOfStatisticalProcessing=1), # Graupel precipitation rate
        # hail precipitation rate (cumul)
        'hailrate': dict(name='unknown', shortName='unknown', parameterCategory=1,
                         parameterNumber=73, typeOfFirstFixedSurface=1, level=0,
                         productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'graupel300hpa': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=201,
                              typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'graupel500hpa': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=201,
                              typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'graupel700hpa': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=201,
                              typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'graupel10m': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=201,
                           typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'graupel100m': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=201,
                            typeOfFirstFixedSurface=103, level=100,  productDefinitionTemplateNumber=1),
        'sd': dict(name='Snow depth water equivalent', shortName='sd',  parameterCategory=1,
                   parameterNumber=60, typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'minvis0m': dict(name='Visibility', shortName='vis', parameterCategory=19, parameterNumber=0,
                         typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                         typeOfStatisticalProcessing=3),
        # minimal visibility due to precipitation
        'minvisprec0m': dict(name='unknown', shortName='unknown', parameterCategory=19, parameterNumber=201,
                             typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                             typeOfStatisticalProcessing=3),
        'avgptype': dict(name='Precipitation type', shortName='ptype', parameterCategory=1, parameterNumber=19,
                         typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                         typeOfStatisticalProcessing=0),
        'maxptype': dict(name='Precipitation type', shortName='ptype', parameterCategory=1, parameterNumber=19,
                         typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                         typeOfStatisticalProcessing=2),
        'evap0m': dict(name='unknown', shortName='unknown', parameterCategory=1, parameterNumber=6,
                       typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                       typeOfStatisticalProcessing=1),
        # potential evaporation
        'evapot': dict(name='unknown', shortName='unknown', parameterCategory=1,
                       parameterNumber=199, typeOfFirstFixedSurface=1, level=0,
                       productDefinitionTemplateNumber=1),
        # net shortwave radiation top of the Atmosphere
        'nswrfTOA': dict(name='Net short wave radiation flux', shortName='nswrf', parameterCategory=4,
                         parameterNumber=9, typeOfFirstFixedSurface=8, level=0,
                         productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'sshf': dict(name='Surface sensible heat flux', shortName='sshf', parameterCategory=0,
                     parameterNumber=11, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'ssrd': dict(name='Surface solar radiation downwards', shortName='ssrd', parameterCategory=4,
                     parameterNumber=7, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'strd': dict(name='Surface thermal radiation downwards', shortName='strd', parameterCategory=5,
                     parameterNumber=3, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'ssrc': dict(name='Surface net solar radiation, clear sky', shortName='ssrc', parameterCategory=4,
                     parameterNumber=11, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        # clear sky upward solar flux ssruc: surface solar radiation upward clear sky
        'ssruc': dict(name='unknown', shortName='unknown', parameterCategory=4, parameterNumber=198,
                 typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=11,
                 typeOfStatisticalProcessing=1),
        'strc': dict(name='Surface net thermal radiation, clear sky', shortName='strc',parameterCategory=5,
                     parameterNumber=6, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'ssr': dict(name='Surface net solar radiation', shortName='ssr', parameterCategory=4,
                    parameterNumber=9, typeOfFirstFixedSurface=1, level=0,
                    productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'ttr': dict(name='Top net thermal radiation', shortName='ttr', parameterCategory=5,
                    parameterNumber=5, typeOfFirstFixedSurface=8, level=0,
                    productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'str': dict(name='Surface net thermal radiation', shortName='str', parameterCategory=5,
                    parameterNumber=5, typeOfFirstFixedSurface=1, level=0,
                    productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'slhf': dict(name='Surface latent heat flux', shortName='slhf', parameterCategory=0,
                     parameterNumber=10, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'ewss': dict(name='Eastward turbulent surface stress', shortName='ewss', parameterCategory=2,
                     parameterNumber=38, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'nsss': dict(name='Northward turbulent surface stress', shortName='nsss',  parameterCategory=2,
                     parameterNumber=37, typeOfFirstFixedSurface=1, level=0,
                     productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=1),
        'u100hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=100, level=100, productDefinitionTemplateNumber=1),
        'u125hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=125, productDefinitionTemplateNumber=1),
        'u150hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=150, productDefinitionTemplateNumber=1),
        'u175hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=175, productDefinitionTemplateNumber=1),
        'u200hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        'u225hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=225, productDefinitionTemplateNumber=1),
        'u250hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'u275hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=275, productDefinitionTemplateNumber=1),
        'u300hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'u350hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        'u400hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        'u450hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=450,  productDefinitionTemplateNumber=1),
        'u500hpa':  dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                         typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'u550hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        'u600hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        'u650hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=650, productDefinitionTemplateNumber=1),
        'u700hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'u750hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        'u800hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        'u850hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        'u900hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        'u925hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        'u950hpa': dict(name='U component of wind', shortName='u', parameterCategory=2,parameterNumber=2,
                        typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        'u1000hpa': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                         typeOfFirstFixedSurface=100, level=1000, productDefinitionTemplateNumber=1),
        'u10m': dict(name='10 metre U wind component', shortName='10u', parameterCategory=2,
                     parameterNumber=2, typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'u20m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                     typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        'u35m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                     typeOfFirstFixedSurface=103, level=35, productDefinitionTemplateNumber=1),
        'u50m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                     typeOfFirstFixedSurface=103, level=50, productDefinitionTemplateNumber=1),
        'u75m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                     typeOfFirstFixedSurface=103, level=75, productDefinitionTemplateNumber=1),
        'u100m': dict(name='100 metre U wind component', shortName='100u', parameterCategory=2,
                      parameterNumber=2,typeOfFirstFixedSurface=103, level=100,
                      productDefinitionTemplateNumber=1),
        'u150m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=150, productDefinitionTemplateNumber=1),
        'u200m': dict(name='200 metre U wind component', shortName='200u', parameterCategory=2,
                      parameterNumber=2, typeOfFirstFixedSurface=103, level=200,
                      productDefinitionTemplateNumber=1),
        'u250m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=250, productDefinitionTemplateNumber=1),
        'u375m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=375, productDefinitionTemplateNumber=1),
        'u500m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=500, productDefinitionTemplateNumber=1),
        'u650m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=625, productDefinitionTemplateNumber=1),
        'u750m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=750, productDefinitionTemplateNumber=1),
        'u875m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                      typeOfFirstFixedSurface=103, level=875, productDefinitionTemplateNumber=1),
        'u1000m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=1000, productDefinitionTemplateNumber=1),
        'u1125m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=1125, productDefinitionTemplateNumber=1),
        'u1250m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=1250, productDefinitionTemplateNumber=1),
        'u1375m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=1375, productDefinitionTemplateNumber=1),
        'u1500m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=1500, productDefinitionTemplateNumber=1),
        'u1750m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=1750, productDefinitionTemplateNumber=1),
        'u2000m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=2000, productDefinitionTemplateNumber=1),
        'u2250m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=2250, productDefinitionTemplateNumber=1),
        'u2500m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=2500, productDefinitionTemplateNumber=1),
        'u2750m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=2750, productDefinitionTemplateNumber=1),
        'u3000m': dict(name='U component of wind', shortName='u', parameterCategory=2, parameterNumber=2,
                       typeOfFirstFixedSurface=103, level=3000, productDefinitionTemplateNumber=1),
        'v10m': dict(name='10 metre V wind component', shortName='10v', parameterCategory=2, parameterNumber=3,
                     typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'v20m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                     typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        'v100hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=100, level=100, productDefinitionTemplateNumber=1),
        'v125hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=125, productDefinitionTemplateNumber=1),
        'v150hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=150, productDefinitionTemplateNumber=1),
        'v175hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=175, productDefinitionTemplateNumber=1),
        'v200hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        'v225hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=225, productDefinitionTemplateNumber=1),
        'v250hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'v275hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=275, productDefinitionTemplateNumber=1),
        'v300hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'v350hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        'v400hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        'v450hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=450, productDefinitionTemplateNumber=1),
        'v500hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'v550hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        'v600hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        'v650hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=650, productDefinitionTemplateNumber=1),
        'v700hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'v750hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        'v800hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        'v850hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        'v900hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        'v925hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        'v950hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                        typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        'v1000hpa': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                         typeOfFirstFixedSurface=100, level=1000, productDefinitionTemplateNumber=1),
        'v35m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                     typeOfFirstFixedSurface=103, level=35, productDefinitionTemplateNumber=1),
        'v50m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                     typeOfFirstFixedSurface=103, level=50, productDefinitionTemplateNumber=1),
        'v75m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                     typeOfFirstFixedSurface=103, level=75, productDefinitionTemplateNumber=1),
        'v100m': dict(name='100 metre V wind component', shortName='100v', parameterCategory=2,
                      parameterNumber=3, typeOfFirstFixedSurface=103, level=100,
                      productDefinitionTemplateNumber=1),
        'v150m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=150, productDefinitionTemplateNumber=1),
        'v200m': dict(name='200 metre V wind component', shortName='200v', parameterCategory=2,
                      parameterNumber=3, typeOfFirstFixedSurface=103, level=200,
                      productDefinitionTemplateNumber=1),
        'v250m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=250, productDefinitionTemplateNumber=1),
        'v375m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=375, productDefinitionTemplateNumber=1),
        'v500m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=500, productDefinitionTemplateNumber=1),
        'v625m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=625, productDefinitionTemplateNumber=1),
        'v750m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=750, productDefinitionTemplateNumber=1),
        'v875m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=875, productDefinitionTemplateNumber=1),
        'v1000m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=1000, productDefinitionTemplateNumber=1),
        'v1125m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=1125, productDefinitionTemplateNumber=1),
        'v1250m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=1250, productDefinitionTemplateNumber=1),
        'v1375m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=1375, productDefinitionTemplateNumber=1),
        'v1500m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=1500, productDefinitionTemplateNumber=1),
        'v1750m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=1750, productDefinitionTemplateNumber=1),
        'v2000m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=2000, productDefinitionTemplateNumber=1),
        'v2250m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=2250, productDefinitionTemplateNumber=1),
        'v2500m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=2500, productDefinitionTemplateNumber=1),
        'v2750m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                      typeOfFirstFixedSurface=103, level=2750, productDefinitionTemplateNumber=1),
        'v3000m': dict(name='V component of wind', shortName='v', parameterCategory=2, parameterNumber=3,
                       typeOfFirstFixedSurface=103, level=3000, productDefinitionTemplateNumber=1),
        'maxugust10m': dict(name='u-component of wind (gust)', shortName='ugust', parameterCategory=2,
                            parameterNumber=23, typeOfFirstFixedSurface=103, level=10,
                            productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=2),
        'maxvgust10m': dict(name='v-component of wind (gust)', shortName='vgust', parameterCategory=2,
                            parameterNumber=24, typeOfFirstFixedSurface=103, level=10,
                            productDefinitionTemplateNumber=11, typeOfStatisticalProcessing=2),
        'z100hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=100, productDefinitionTemplateNumber=1),
        'z125hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=125, productDefinitionTemplateNumber=1),
        'z150hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=150, productDefinitionTemplateNumber=1),
        'z175hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=175, productDefinitionTemplateNumber=1),
        'z200hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                  typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        'z225hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=225, productDefinitionTemplateNumber=1),
        'z250hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'z275hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=275, productDefinitionTemplateNumber=1),
        'z300hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'z350hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        'z400hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        'z450hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=450, productDefinitionTemplateNumber=1),
        'z500hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'z550hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        'z600hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        'z650hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=650,  productDefinitionTemplateNumber=1),
        'z700hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'z750hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        'z800hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        'z850hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                 typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        'z900hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        'z925hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                        typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        'z950hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                        typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        'z1000hpa': dict(name='Geopotential', shortName='z', parameterCategory=3, parameterNumber=4,
                         typeOfFirstFixedSurface=100, level=1000, productDefinitionTemplateNumber=1),
        'clwc10m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                 parameterNumber=83, typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'clwc20m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                 parameterNumber=83, typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        'clwc35m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83, typeOfFirstFixedSurface=103, level=35, productDefinitionTemplateNumber=1),
        'clwc50m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                     parameterNumber=83, typeOfFirstFixedSurface=103, level=50, productDefinitionTemplateNumber=1),
        'clwc75m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                     parameterNumber=83, typeOfFirstFixedSurface=103, level=75, productDefinitionTemplateNumber=1),
        'clwc100m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83, typeOfFirstFixedSurface=103, level=100, productDefinitionTemplateNumber=1),
        'clwc150m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83, typeOfFirstFixedSurface=103, level=150, productDefinitionTemplateNumber=1),
        'clwc200m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=200, productDefinitionTemplateNumber=1),
        'clwc250m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=250, productDefinitionTemplateNumber=1),
        'clwc375m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=375, productDefinitionTemplateNumber=1),
        'clwc500m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=500, productDefinitionTemplateNumber=1),
        'clwc625m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=625, productDefinitionTemplateNumber=1),
        'clwc750m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=750, productDefinitionTemplateNumber=1),
        'clwc875m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                     parameterNumber=83,typeOfFirstFixedSurface=103, level=875, productDefinitionTemplateNumber=1),
        'clwc1000m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=1000, productDefinitionTemplateNumber=1),
        'clwc1125m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                     parameterNumber=83,typeOfFirstFixedSurface=103, level=1125, productDefinitionTemplateNumber=1),
        'clwc1250m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                     parameterNumber=83,typeOfFirstFixedSurface=103, level=1250, productDefinitionTemplateNumber=1),
        'clwc1375m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=1375, productDefinitionTemplateNumber=1),
        'clwc1500m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=1500, productDefinitionTemplateNumber=1),
        'clwc1750m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=1750, productDefinitionTemplateNumber=1),
        'clwc2000m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                     parameterNumber=83,typeOfFirstFixedSurface=103, level=2000, productDefinitionTemplateNumber=1),
        'clwc2250m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                 parameterNumber=83,typeOfFirstFixedSurface=103, level=2250, productDefinitionTemplateNumber=1),
        'clwc2500m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=2500, productDefinitionTemplateNumber=1),
        'clwc2750m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                    parameterNumber=83,typeOfFirstFixedSurface=103, level=2750, productDefinitionTemplateNumber=1),
        'clwc3000m': dict(name='Specific cloud liquid water content', shortName='clwc', parameterCategory=1,
                          parameterNumber=83, typeOfFirstFixedSurface=103, level=3000,
                          productDefinitionTemplateNumber=1),
        'ciwc10m': dict(name='Specific cloud ice water content', shortName='ciwc', parameterCategory=1,
                        parameterNumber=84, typeOfFirstFixedSurface=103, level=10,
                        productDefinitionTemplateNumber=1),
        'ciwc100m': dict(name='Specific cloud ice water content', shortName='ciwc', parameterCategory=1,
                         parameterNumber=84, typeOfFirstFixedSurface=103, level=100,
                         productDefinitionTemplateNumber=1),
        'cswc10m': dict(name='Specific snow water content', shortName='cswc', parameterCategory=1,
                        parameterNumber=86, typeOfFirstFixedSurface=103, level=10,
                        productDefinitionTemplateNumber=1),
        'cswc100m': dict(name='Specific snow water content', shortName='cswc', parameterCategory=1,
                         parameterNumber=86, typeOfFirstFixedSurface=103, level=100,
                         productDefinitionTemplateNumber=1),
        'crwc10m': dict(   name='Specific rain water content', shortName='crwc', parameterCategory=1,
                           parameterNumber=85, typeOfFirstFixedSurface=103, level=10,
                           productDefinitionTemplateNumber=1),
        'crwc100m': dict(name='Specific rain water content', shortName='crwc', parameterCategory=1,
                         parameterNumber=85,typeOfFirstFixedSurface=103, level=100,
                         productDefinitionTemplateNumber=1),
        'tciwv': dict(name='Total column integrated water vapour', shortName='tciwv', parameterCategory=1,
                      parameterNumber=64,typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        # total cloud cover (ground level)
        'tcc0m': dict(name='unknown', shortName='unknown', parameterCategory=6, parameterNumber=1,
                      typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'hcc0m': dict(name='High cloud cover', shortName='hcc', parameterCategory=6, parameterNumber=5,
                      typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'mcc0m': dict(name='Medium cloud cover', shortName='mcc', parameterCategory=6, parameterNumber=4,
                      typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'lcc0m': dict(name='Low cloud cover', shortName='lcc', parameterCategory=6, parameterNumber=3,
                      typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'cc10m': dict(name='Fraction of cloud cover', shortName='cc', parameterCategory=6, parameterNumber=32,
                      typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'cc20m': dict(name='Fraction of cloud cover', shortName='cc', parameterCategory=6, parameterNumber=32,
                      typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        'r2m': dict(name='2 metre relative humidity', shortName='2r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=103, level=2, productDefinitionTemplateNumber=1),
        'r100hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=100, level=100, productDefinitionTemplateNumber=1),
        'r125hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=100, level=125, productDefinitionTemplateNumber=1),
        'r150hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=150, productDefinitionTemplateNumber=1),
        'r175hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=100, level=175, productDefinitionTemplateNumber=1),
        'r200hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        'r225hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=225, productDefinitionTemplateNumber=1),
        'r250hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'r275hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=275, productDefinitionTemplateNumber=1),
        'r300hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'r350hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        'r400hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        'r450hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=450, productDefinitionTemplateNumber=1),
        'r500hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'r550hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        'r600hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        'r650hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=100, level=650, productDefinitionTemplateNumber=1),
        'r700hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'r750hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                 typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        'r800hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        'r850hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        'r900hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        'r925hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                        typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        'r950hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                        typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        'r100hpa': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                        typeOfFirstFixedSurface=100, level=1000, productDefinitionTemplateNumber=1),
        'r10m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'r20m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        'r35m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=35, productDefinitionTemplateNumber=1),
        'r50m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=50, productDefinitionTemplateNumber=1),
        'r75m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=75, productDefinitionTemplateNumber=1),
        'r100m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=100, productDefinitionTemplateNumber=1),
        'r150m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=150, productDefinitionTemplateNumber=1),
        'r200m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=200, productDefinitionTemplateNumber=1),
        'r250m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=250, productDefinitionTemplateNumber=1),
        'r375m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                    typeOfFirstFixedSurface=103, level=375, productDefinitionTemplateNumber=1),
        'r500m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                      typeOfFirstFixedSurface=103, level=500, productDefinitionTemplateNumber=1),
        'r625m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                      typeOfFirstFixedSurface=103, level=625, productDefinitionTemplateNumber=1),
        'r750m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                      typeOfFirstFixedSurface=103, level=750, productDefinitionTemplateNumber=1),
        'r875m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                      typeOfFirstFixedSurface=103, level=875, productDefinitionTemplateNumber=1),
        'r1000m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=1000, productDefinitionTemplateNumber=1),
        'r1125m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=1125, productDefinitionTemplateNumber=1),
        'r1250m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=1250, productDefinitionTemplateNumber=1),
        'r1375m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=1375, productDefinitionTemplateNumber=1),
        'r1500m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=1500, productDefinitionTemplateNumber=1),
        'r1750m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=1750, productDefinitionTemplateNumber=1),
        'r2000m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=2000, productDefinitionTemplateNumber=1),
        'r2250m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=2250, productDefinitionTemplateNumber=1),
        'r2500m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=2500, productDefinitionTemplateNumber=1),
        'r2750m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=2750, productDefinitionTemplateNumber=1),
        'r3000m': dict(name='Relative humidity', shortName='r', parameterCategory=1, parameterNumber=1,
                       typeOfFirstFixedSurface=103, level=3000, productDefinitionTemplateNumber=1),
        'tke10m': dict(name='Turbulent kinetic energy', shortName='tke', parameterCategory=19,
                       parameterNumber=11, typeOfFirstFixedSurface=103, level=10,
                       productDefinitionTemplateNumber=1),
        'tke100m': dict(name='Turbulent kinetic energy', shortName='tke', parameterCategory=19,
                        parameterNumber=11, typeOfFirstFixedSurface=103, level=100,
                        productDefinitionTemplateNumber=1),
        'tke150m': dict(name='Turbulent kinetic energy', shortName='tke', parameterCategory=19,
                        parameterNumber=11, typeOfFirstFixedSurface=103, level=150,
                        productDefinitionTemplateNumber=1),
        'papt200hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt', parameterCategory=0,
                    parameterNumber=3, typeOfFirstFixedSurface=100, level=200,
                    productDefinitionTemplateNumber=1),
        'papt225hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt', parameterCategory=0,
                    parameterNumber=3, typeOfFirstFixedSurface=100, level=225,
                    productDefinitionTemplateNumber=1),
        'papt250hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt', parameterCategory=0,
                    parameterNumber=3, typeOfFirstFixedSurface=100, level=250,
                    productDefinitionTemplateNumber=1),
        'papt275hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=275,
                    productDefinitionTemplateNumber=1),
        'papt300hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=300,
                    productDefinitionTemplateNumber=1),
        'papt350hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=350,
                    productDefinitionTemplateNumber=1),
        'papt400hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=400,
                    productDefinitionTemplateNumber=1),
        'papt450hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=450,
                    productDefinitionTemplateNumber=1),
        'papt500hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=500,
                    productDefinitionTemplateNumber=1),
        'papt550hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3,typeOfFirstFixedSurface=100, level=550,
                    productDefinitionTemplateNumber=1),
        'papt600hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=600,
                    productDefinitionTemplateNumber=1),
        'papt650hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=650,
                    productDefinitionTemplateNumber=1),
        'papt700hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=700,
                    productDefinitionTemplateNumber=1),
        'papt750hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                 parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=750,
                 productDefinitionTemplateNumber=1),
        'papt800hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=800,
                    productDefinitionTemplateNumber=1),
        'papt850hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=850,
                    productDefinitionTemplateNumber=1),
        'papt900hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=900,
                    productDefinitionTemplateNumber=1),
        'papt925hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=925,
                    productDefinitionTemplateNumber=1),
        'papt950hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=950,
                    productDefinitionTemplateNumber=1),
        'papt1000hpa': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=100, level=1000,
                    productDefinitionTemplateNumber=1),
        'papt10m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=10,
                    productDefinitionTemplateNumber=1),
        'papt20m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=20,
                    productDefinitionTemplateNumber=1),
        'papt35m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=35,
                    productDefinitionTemplateNumber=1),
        'papt50m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=50,
                    productDefinitionTemplateNumber=1),
        'papt75m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=75,
                    productDefinitionTemplateNumber=1),
        'papt100m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=100,
                    productDefinitionTemplateNumber=1),
        'papt150m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=150,
                    productDefinitionTemplateNumber=1),
        'papt200m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=200,
                    productDefinitionTemplateNumber=1),
        'papt250m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                    parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=250,
                    productDefinitionTemplateNumber=1),
        'papt375m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                         parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=375,
                         productDefinitionTemplateNumber=1),
        'papt500m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                         parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=500,
                         productDefinitionTemplateNumber=1),
        'papt625m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                         parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=625,
                         productDefinitionTemplateNumber=1),
        'papt750m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                         parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=750,
                         productDefinitionTemplateNumber=1),
        'papt875m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                         parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=875,
                         productDefinitionTemplateNumber=1),
        'papt1000m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt', parameterCategory=0,
                          parameterNumber=3, typeOfFirstFixedSurface=103, level=1000,
                          productDefinitionTemplateNumber=1),
        'papt1125m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=1125,
                          productDefinitionTemplateNumber=1),
        'papt1250m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=1250,
                          productDefinitionTemplateNumber=1),
        'papt1375m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=1375,
                          productDefinitionTemplateNumber=1),
        'papt1500m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=1500,
                          productDefinitionTemplateNumber=1),
        'papt1750m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=1750,
                          productDefinitionTemplateNumber=1),
        'papt2000m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=2000,
                          productDefinitionTemplateNumber=1),
        'papt2250m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=2250,
                          productDefinitionTemplateNumber=1),
        'papt2500m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=2500,
                          productDefinitionTemplateNumber=1),
        'papt2750m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=2750,
                          productDefinitionTemplateNumber=1),
        'papt3000m': dict(name='Pseudo-adiabatic potential temperature', shortName='papt',
                          parameterCategory=0, parameterNumber=3, typeOfFirstFixedSurface=103, level=3000,
                          productDefinitionTemplateNumber=1),
        'hpbl': dict(name='Planetary boundary layer height', shortName='hpbl', parameterCategory=3,
                    parameterNumber=18, typeOfFirstFixedSurface=1, level=0,
                    productDefinitionTemplateNumber=1),
        # reflectivity
        'refl200hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                           typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        'refl250hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'refl300hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'refl350hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        'refl400hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        'refl450hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=450, productDefinitionTemplateNumber=1),
        'refl500hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'refl550hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        'refl600hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        'refl650hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=650, productDefinitionTemplateNumber=1),
        'refl700hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'refl750hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        'refl800hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        'refl850hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        'refl900hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        'refl950hpa': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=4,
                    typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        # Equivalent radar reflectivity factor for snow
        'reflfactorsnow': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=193,
                               typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'refl0m': dict(name='unknown', shortName='unknown', parameterCategory=16, parameterNumber=195,
                       typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        # eddy dissipation rate
        'edr250hpa': dict(name='unknown', shortName='unknown', parameterCategory=19, parameterNumber=199,
                    typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'edr950hpa': dict(name='unknown', shortName='unknown', parameterCategory=19, parameterNumber=199,
                    typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        'w100hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=100, productDefinitionTemplateNumber=1),
        'w125hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=125, productDefinitionTemplateNumber=1),
        'w125hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=150, productDefinitionTemplateNumber=1),
        'w175hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=175, productDefinitionTemplateNumber=1),
        'w200hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=200, productDefinitionTemplateNumber=1),
        'w225hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=225, productDefinitionTemplateNumber=1),
        'w250hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                    typeOfFirstFixedSurface=100, level=250, productDefinitionTemplateNumber=1),
        'w275hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=275, productDefinitionTemplateNumber=1),
        'w300hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'w350hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=350, productDefinitionTemplateNumber=1),
        'w400hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=400, productDefinitionTemplateNumber=1),
        'w450hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=450, productDefinitionTemplateNumber=1),
        'w500hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=500, productDefinitionTemplateNumber=1),
        'w550hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=550, productDefinitionTemplateNumber=1),
        'w600hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=600, productDefinitionTemplateNumber=1),
        'w650hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=650, productDefinitionTemplateNumber=1),
        'w700hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=700, productDefinitionTemplateNumber=1),
        'w750hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=750, productDefinitionTemplateNumber=1),
        'w800hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=800, productDefinitionTemplateNumber=1),
        'w850hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=850, productDefinitionTemplateNumber=1),
        'w900hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=900, productDefinitionTemplateNumber=1),
        'w925hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=925, productDefinitionTemplateNumber=1),
        'w950hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                        typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
        'w1000hpa': dict(name='Vertical velocity', shortName='w', parameterCategory=2, parameterNumber=8,
                         typeOfFirstFixedSurface=100, level=1000, productDefinitionTemplateNumber=1),
        'prmsl': dict(name='Pressure reduced to MSL', shortName='prmsl', parameterCategory=3,
                      parameterNumber=1, typeOfFirstFixedSurface=101, level=0,
                      productDefinitionTemplateNumber=1),
        'presechotop18': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                              typeOfFirstFixedSurface=25, level=18, productDefinitionTemplateNumber=1),
        'pres0m': dict(name='Surface pressure', shortName='sp', parameterCategory=3, parameterNumber=0,
                       typeOfFirstFixedSurface=1, level=0, productDefinitionTemplateNumber=1),
        'pres10m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=10, productDefinitionTemplateNumber=1),
        'pres20m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=20, productDefinitionTemplateNumber=1),
        'pres35m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=35, productDefinitionTemplateNumber=1),
        'pres50m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=50, productDefinitionTemplateNumber=1),
        'pres75m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=75, productDefinitionTemplateNumber=1),
        'pres100m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=100, productDefinitionTemplateNumber=1),
        'pres150m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=150, productDefinitionTemplateNumber=1),
        'pres200m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                    typeOfFirstFixedSurface=103, level=200, productDefinitionTemplateNumber=1),
        'pres250m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                         typeOfFirstFixedSurface=103, level=250, productDefinitionTemplateNumber=1),
        'pres375m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                         typeOfFirstFixedSurface=103, level=375, productDefinitionTemplateNumber=1),
        'pres500m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                         typeOfFirstFixedSurface=103, level=500, productDefinitionTemplateNumber=1),
        'pres625m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                         typeOfFirstFixedSurface=103, level=625, productDefinitionTemplateNumber=1),
        'pres750m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                         typeOfFirstFixedSurface=103, level=750, productDefinitionTemplateNumber=1),
        'pres875m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                         typeOfFirstFixedSurface=103, level=875, productDefinitionTemplateNumber=1),
        'pres1000m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=1000, productDefinitionTemplateNumber=1),
        'pres1125m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=1125, productDefinitionTemplateNumber=1),
        'pres1250m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=1250, productDefinitionTemplateNumber=1),
        'pres1375m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=1375, productDefinitionTemplateNumber=1),
        'pres1500m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=1500, productDefinitionTemplateNumber=1),
        'pres1750m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=1750, productDefinitionTemplateNumber=1),
        'pres2000m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=2000, productDefinitionTemplateNumber=1),
        'pres2250m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=2250, productDefinitionTemplateNumber=1),
        'pres2500m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=2500, productDefinitionTemplateNumber=1),
        'pres2750m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=2750, productDefinitionTemplateNumber=1),
        'pres3000m': dict(name='Pressure', shortName='pres', parameterCategory=3, parameterNumber=0,
                          typeOfFirstFixedSurface=103, level=3000, productDefinitionTemplateNumber=1),
        'd300hpa': dict(name='Divergence', shortName='d', parameterCategory=2, parameterNumber=13,
                    typeOfFirstFixedSurface=100, level=300, productDefinitionTemplateNumber=1),
        'd950hpa': dict(name='Divergence', shortName='d', parameterCategory=2, parameterNumber=13,
                    typeOfFirstFixedSurface=100, level=950, productDefinitionTemplateNumber=1),
                # Brightnesstemperature
        'BT16129032': dict(name='unknown', shortName='unknown', parameterCategory=5, parameterNumber=7,
                    productDefinitionTemplateNumber=33, NB=1, satelliteSeries=0, satelliteNumber=0, 
                    instrumentType=0, scaleFactorOfCentralWaveNumber=2,
                    scaledValueOfCentralWaveNumber=16129032),
        'BT9259259': dict(name='unknown', shortName='unknown', parameterCategory=5, parameterNumber=7,
                    productDefinitionTemplateNumber=33, NB=1, satelliteSeries=0, satelliteNumber=0,
                    instrumentType=0, scaleFactorOfCentralWaveNumber=2,
                    scaledValueOfCentralWaveNumber=9259259),
        'capeins0_3000': dict(name='Convective Available Potential Energy instantaneous',
                              shortName='CAPE_INS',
                    parameterCategory=7, parameterNumber=6, typeOfFirstFixedSurface=1, level=0, topLevel=0,
                    typeOfSecondFixedSurface=103, bottomLevel=3000, productDefinitionTemplateNumber=1)}

module = sys.modules[__name__]
for name, gribdict in vars.items():
    setattr(module, name,
            NativeVariable(model_name=model, name=gribdict, outname=name))
